variable "region" {}
variable "environment" {}
variable "system_name" {}
variable "vpc_id" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "alb_sg_id" {}
variable "allow_access_pl" {}
variable "azs" {}